[project]
name = "chatecnu-cli"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=2.16.0",
    "python-dotenv>=1.2.1",
]
